In [1]:
import scipy.stats as spst
import scipy
import seaborn as sns
import numpy as np
import pandas as pd
import qrbook_funcs as qf
from scipy import stats
from tabulate import tabulate
from arch import arch_model
import math
import statistics 
import matplotlib.pyplot as plt
%matplotlib inline

#### Q1. Find two random variable 1) Negative Pearson with positive Spearman correlation. 2) Positive Pearson with negative Spearman correlation

In [2]:
x=[1,1,1,1,100]
y=[100,3,2,2,3]
pearson1=spst.pearsonr(x,y)
spearman1=spst.spearmanr(x,y)
print("First one: negative pearson but positive Spearman")
print("Pearson correlation is: ", pearson1[0])
print("Spearman correlation is: ", spearman1[0])

First one: negative pearson but positive Spearman
Pearson correlation is:  -0.2435737300641969
Spearman correlation is:  0.18633899812498247

In [3]:
xx=np.asarray(x)*(-1)
yy=y
pearson2=spst.pearsonr(xx,yy)
spearman2=spst.spearmanr(xx,yy)
print("Second one: positive pearson but negative Spearman")
print("Pearson correlation is: ", pearson2[0])
print("Spearman correlation is: ", spearman2[0])

Second one: positive pearson but negative Spearman
Pearson correlation is:  0.2435737300641969
Spearman correlation is:  -0.18633899812498247

#### Q2. Compute the average correlation

In [4]:
# read data
data=pd.read_excel('Dow 2013 vol.xlsx')

In [5]:
data

                                      Company    Price  Implied Vol    Weight
0                                   MMM 3M Co   106.40       0.1380  0.056302
1                                AA Alcoa Inc     8.63       0.2920  0.004567
2                     AXP American Express Co    66.09       0.1600  0.034972
3                                  T AT&T Inc    36.43       0.1340  0.019277
4                    BAC Bank of America Corp    12.57       0.2640  0.006651
5                                BA Boeing Co    86.43       0.1700  0.045735
6                         CAT Caterpillar Inc    88.83       0.1820  0.047005
7                            CVX Chevron Corp   119.68       0.1350  0.063329
8                      CSCO Cisco Systems Inc    21.92       0.1730  0.011599
9          DD E. I. du Pont de Nemours and Co    49.90       0.1300  0.026405
10                       XOM Exxon Mobil Corp    89.37       0.1120  0.047290
11                     GE General Electric Co    23.44       0.1640  0.012403
12                     HPQ Hewlett-Packard Co    22.18       0.2730  0.011737
13                          HD Home Depot Inc    69.05       0.1590  0.036538
14                            INTC Intel Corp    21.38       0.2060  0.011313
15  IBM International Business Machines Co...   214.92       0.1420  0.113726
16                      JNJ Johnson & Johnson    79.19       0.1020  0.041904
17                  JPM JPMorgan Chase and Co    50.02       0.2060  0.026468
18                        MCD McDonald's Corp    99.67       0.1170  0.052741
19                         MRK Merck & Co Inc    44.09       0.1330  0.023330
20                        MSFT Microsoft Corp    28.04       0.1600  0.014837
21                             PFE Pfizer Inc    28.02       0.1330  0.014827
22                     PG Procter & Gamble Co    76.34       0.1290  0.040396
23                        KO The Coca-Cola Co    38.83       0.1330  0.020547
24                TRV Travelers Companies Inc    82.28       0.1420  0.043539
25               UTX United Technologies Corp    93.28       0.1370  0.049359
26                 UNH UnitedHealth Group Inc    54.73       0.1900  0.028961
27              VZ Verizon Communications Inc    48.02       0.1430  0.025410
28                    WMT Wal-Mart Stores Inc    72.50       0.1250  0.038364
29                         DIS Walt Disney Co    57.58       0.1510  0.030469
30                        Dow Jones Index DJX  1889.81       0.0858       NaN

In [6]:
# add one more column
data['vi']=data['Implied Vol'] * data['Weight']
data['vi_square']=data['vi']**2

In [7]:
data

,Company,Price,Implied Vol,Weight,vi,vi_square
0,MMM 3M Co,106.40,0.1380,0.056302,0.007770,0.000060
1,AA Alcoa Inc,8.63,0.2920,0.004567,0.001334,0.000002
2,AXP American Express Co,66.09,0.1600,0.034972,0.005596,0.000031
3,T AT&T Inc,36.43,0.1340,0.019277,0.002583,0.000007
4,BAC Bank of America Corp,12.57,0.2640,0.006651,0.001756,0.000003
5,BA Boeing Co,86.43,0.1700,0.045735,0.007775,0.000060
6,CAT Caterpillar Inc,88.83,0.1820,0.047005,0.008555,0.000073
7,CVX Chevron Corp,119.68,0.1350,0.063329,0.008549,0.000073
8,CSCO Cisco Systems Inc,21.92,0.1730,0.011599,0.002007,0.000004
9,DD E. I. du Pont de Nemours and Co,49.90,0.1300,0.026405,0.003433,0.000012
10,XOM Exxon Mobil Corp,89.37,0.1120,0.047290,0.005296,0.000028
11,GE General Electric Co,23.44,0.1640,0.012403,0.002034,0.000004
12,HPQ Hewlett-Packard Co,22.18,0.2730,0.011737,0.003204,0.000010
13,HD Home Depot Inc,69.05,0.1590,0.036538,0.005810,0.000034
14,INTC Intel Corp,21.38,0.2060,0.011313,0.002330,0.000005
15,IBM International Business Machines Co...,214.92,0.1420,0.113726,0.016149,0.000261
16,JNJ Johnson & Johnson,79.19,0.1020,0.041904,0.004274,0.000018
17,JPM JPMorgan Chase and Co,50.02,0.2060,0.026468,0.005452,0.000030
18,MCD McDonald's Corp,99.67,0.1170,0.052741,0.006171,0.000038
19,MRK Merck & Co Inc,44.09,0.1330,0.023330,0.003103,0.000010
20,MSFT Microsoft Corp,28.04,0.1600,0.014837,0.002374,0.000006
21,PFE Pfizer Inc,28.02,0.1330,0.014827,0.001972,0.000004
22,PG Procter & Gamble Co,76.34,0.1290,0.040396,0.005211,0.000027
23,KO The Coca-Cola Co,38.83,0.1330,0.020547,0.002733,0.000007
24,TRV Travelers Companies Inc,82.28,0.1420,0.043539,0.006183,0.000038
25,UTX United Technologies Corp,93.28,0.1370,0.049359,0.006762,0.000046
26,UNH UnitedHealth Group Inc,54.73,0.1900,0.028961,0.005503,0.000030
27,VZ Verizon Communications Inc,48.02,0.1430,0.025410,0.003634,0.000013
28,WMT Wal-Mart Stores Inc,72.50,0.1250,0.038364,0.004796,0.000023
29,DIS Walt Disney Co,57.58,0.1510,0.030469,0.004601,0.000021
30,Dow Jones Index DJX,1889.81,0.0858,NaN,NaN,NaN

In [8]:
# compute sum of vi
sum_vi=sum(data['vi'][0:-1])

# compute average correlation
var_portfolio=data.iloc[30,2]**2 # portfolio var

nominator=var_portfolio-sum(data['vi_square'][0:-1])
denominator=sum_vi**2-sum(data['vi_square'][0:-1])

# compute the final result
average_corr=nominator / denominator

In [9]:
print("The average correlation is: ", average_corr)

The average correlation is:  0.30959733628704894

### Q3. Assuming their default times are bound by a normal copula, what is the chance that both bonds default before two years are up?

In [10]:
# Generate random samples from multivariate normal with correlation .2
mvnorm = stats.multivariate_normal(mean=[0, 0], cov=[[1., 0.2], 
                                                     [0.2, 1.]])
n=1000000
x = mvnorm.rvs(n)

In [11]:
#h = sns.jointplot(x[:, 0], x[:, 1], kind='kde', stat_func=None);
#h.set_axis_labels('X1', 'X2', fontsize=16);

In [12]:
# Uniformify the marginals
norm = stats.norm()
x_unif = norm.cdf(x) # x_unif is probablity now and thus every number is between 0-1, which is uniform

In [13]:
#h = sns.jointplot(x_unif[:, 0], x_unif[:, 1], kind='hex', stat_func=None)
#h.set_axis_labels('Y1', 'Y2', fontsize=16);

In [14]:
# inverse cdf of exponential functions. transform to correlated exponentially distributed variable
m1 = spst.expon(scale=1/0.07)
m2 = spst.expon(scale=1/0.1)

# this is the quantile function to transform from probability to quantile. In other words, this is the inverse CDF
x1_trans=m1.ppf(x_unif[:,0]) 
x2_trans=m2.ppf(x_unif[:,1])

# save transformed result to a dataframe
bond_t = pd.DataFrame({'bond1': x1_trans, 'bond2': x2_trans}, columns=['bond1', 'bond2'])

In [15]:
bond_t.head(5)

       bond1      bond2
0  13.045349  14.919345
1   5.871001  19.572645
2   9.986836  12.927978
3   8.370773   6.105226
4   5.478481   6.295220

In [16]:
# Count how many in the sample both bonds have less than t=2
both_less_2=bond_t[(bond_t['bond1']<2) & (bond_t['bond2']<2)].count()

In [17]:
probability=both_less_2[0]/n
print("The probability that both bonds default before 2 years is: ", probability)

The probability that both bonds default before 2 years is:  0.036139

In [18]:
#h = sns.jointplot(x1_trans, x2_trans, kind='kde', xlim=(0, 138), ylim=(0, 100), stat_func=None);
#h.set_axis_labels('Maximum river level', 'Probablity of flooding', fontsize=16);

In [19]:
#?scipy.stats.expon

In [20]:
##?stats.multivariate_normal

### Q4

In [35]:
# get data ready
import pandas as pd

ff_head='http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/'
ff_foot="_3_Factors_Daily_CSV.zip"
ff_names=["Europe","North_America","Japan"]

for name_index in range(len(ff_names)):
    print("Inputting ",ff_names[name_index])
    ffurl=ff_head+ff_names[name_index]+ff_foot
    #Skip the six header rows
    df_region = pd.read_csv(ffurl, skiprows=4)
    #Standardize name of Date column and market return column
    col0=df_region.columns[0]
    df_region.rename(columns={col0:'Date'},inplace=True)
    df_region.rename(columns={"Mkt-RF":ff_names[name_index]},inplace=True)
    #Merge into aggregate
    if name_index == 0:
        df_returns=df_region[df_region.columns[0:2]]
    else:
        df_returns = df_returns.merge(df_region[df_region.columns[0:2]], 
                            left_on='Date', right_on='Date')
        
#Convert to log-returns
df_logs_day=np.log(1+df_returns[df_returns.columns[1:]]/100)
df_logs_day.insert(0,"Date",df_returns["Date"],True)
#Remove the partial year at the end
lastyear=np.unique(list(map(int,df_logs_day["Date"].values/10000)))[-1]
#Find the first index of the latest (partial) year in first_drop
for i in range(len(df_logs_day)):
    thisyear=int(df_logs_day.iloc[i]["Date"]/10000)
    if thisyear == lastyear:
        first_drop=i
        break
 
# Remove partial year at the end
df_logs_day.drop(df_logs_day.index[first_drop:],inplace=True)


import datetime
def find_day(date_yyyymmdd):
    #Find day of week of a date
    #in the form YYYYMMDD
    date_int=int(date_yyyymmdd)
    year=int(date_int/10000)
    month=int((date_int-year*10000)/100)
    day=int(date_int) % 100
    return(datetime.datetime(year,month,day).weekday())
#Done with find_day

#Convert to weekly to avoid asynchronous trading effects Wednesday-Wednesday
wednesday = 2  #Monday = 0
ndays=len(df_logs_day)
initialized = False

#Create empty dataframe for weekly log-returns
df_logs=df_logs_day.drop(df_logs_day.index[0:])

for t in range(ndays):
    if not initialized:
        week_sum = df_logs_day.iloc[t]
        initialized = True
    else:
        week_sum += df_logs_day.iloc[t]
    if find_day(df_logs_day.iloc[t]["Date"])==wednesday:
        df_logs=df_logs.append(week_sum,ignore_index=True)
        df_logs.iloc[-1,0]=int(df_logs_day.iloc[t]["Date"])
        initialized=False

periodicity=52   #For use in later code segments

nobs=len(df_logs)
print(nobs,"observations starting",int(df_logs.iloc[0]["Date"]), \
      "ending",int(df_logs.iloc[-1]["Date"]))

overallmean=np.mean(df_logs)
overallstd=np.std(df_logs)
tickerlist=df_logs.columns[1:]   #skip the date column

# #Get GARCH params for each ticker
# gparams=[]
# initparams=[.12,.85,.6]
# stgs=[] #Save the running garch sigma's
# for it,ticker in enumerate(tickerlist):
#     #Note ORDER MATTERS: make sure values are in date order
#     gparams.append(qf.Garch11Fit(initparams,df_logs.sort_values(by="Date")[ticker]))
#     a,b,c=gparams[it]
    
#     #Create time series of sigmas
#     t=len(df_logs[ticker])
#     minimal=10**(-20)
#     stdgarch=np.zeros(t)
#     stdgarch[0]=overallstd[ticker]
    
#     #Compute GARCH(1,1) stddev's from data given parameters
#     for i in range(1,t):
#         #Note offset - i-1 observation of data
#         #is used for i estimate of std deviation
#         previous=stdgarch[i-1]**2
#         var=c+b*previous+a*(df_logs.sort_values(by="Date")[ticker][i-1]-overallmean[ticker])**2
#         stdgarch[i]=np.sqrt(var)

#     #Save for later de-GARCHing
#     stgs.append(stdgarch)


#Demeaned, DeGARCHed series go in dfeps
dfeps=df_logs.sort_values(by="Date").copy()
# for it,ticker in enumerate(tickerlist):
#     dfeps[ticker]-=overallmean[ticker]
#     for i in range(len(dfeps)):
#         dfeps[ticker].iloc[i]/=stgs[it][i]
#     print(ticker)
#     print('    DeGARCHed Mean:',np.mean(dfeps[ticker]))
    
#     print('    Raw annualized Std Dev:',np.sqrt(periodicity)*overallstd[ticker])
#     print('    DeGARCHed Std Dev:',np.std(dfeps[ticker]))
    
#     print('    Raw excess kurtosis:',spst.kurtosis(df_logs[ticker]))
#     print('    DeGARCHed Excess Kurtosis:',spst.kurtosis(dfeps[ticker]))

InData=np.array(dfeps[tickerlist])

Inputting  Europe
Inputting  North_America
Inputting  Japan
1487 observations starting 19900704 ending 20181226

In [36]:
# mean reverting function
def MeanRevCorrObj(params):
    #Compute time series of quasi-correlation
    #matrices from InData using mean reverting
    #formula 9.45. Standardize them and apply
    #formula 9.49. Returns scalar 9.49
    
    #Extract parameters
    alpha,beta=params
    #Enforce bounds
    if alpha<0 or beta<0:
        return(10**20)
    elif (alpha+beta)>.999:
        return(10**20)
    
    obj9p39=0
    
    #Initial omega is obtained through correlation targeting
    Rlong=np.corrcoef(InData.T)
    previousq=np.identity(len(InData[0]))
    
    #Form new shock matrix
    for i in range(len(InData)):
        #standardize previous q matrix and compute contribution to objective function
        stdmtrx=np.diag([1/np.sqrt(previousq[s,s]) for s in range(len(previousq))])
        previousr=np.matmul(stdmtrx,np.matmul(previousq,stdmtrx))
        #objective function
        obj9p39+=np.log(np.linalg.det(previousr))
        shockvec=np.array(InData[i])
        vec1=np.matmul(shockvec,np.linalg.inv(previousr))
        #This makes obj9p39 into a 1,1 matrix
        obj9p39+=np.matmul(vec1,shockvec)
              
        #Update q matrix
        shockvec=np.mat(shockvec)
        shockmat=np.matmul(shockvec.T,shockvec)
        previousq=(1-alpha-beta)*Rlong+alpha*shockmat+beta*previousq
    return(obj9p39[0,0])
#Done with MeanRevCorrObj

In [37]:
# find optimal alpha and beta and halflife
import scipy.optimize as scpo
#alpha and beta positive
corr_bounds = scpo.Bounds([0,0],[np.inf,np.inf])
#Sum of alpha and beta is less than 1
corr_linear_constraint = scpo.LinearConstraint([[1, 1]],[0],[.999])

initparams=[.02,.93]
results = scpo.minimize(MeanRevCorrObj, \
        initparams, \
        method='trust-constr', \
        jac='2-point', \
        hess=scpo.SR1(), \
        bounds=corr_bounds, \
        constraints=corr_linear_constraint)

alpha,beta=results.x
print('Optimal alpha, beta:',alpha,beta)
print('Optimal objective function:',results.fun)
halflife=-np.log(2)/np.log(1-alpha)
print('Half-life (years):',halflife/periodicity)

C:\Users\wangc\AppData\Roaming\Python\Python36\site-packages\scipy\optimize\_trustregion_constr\canonical_constraint.py:148: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  c.keep_feasible for c in canonical_constraints)), dtype=bool)

Optimal alpha, beta: 0.003081993833229487 1.053386057635158e-05
Optimal objective function: -1585.9550762936208
Half-life (years): 4.31837392153614